In [ ]:
import numpy as np

Kode 1

Buatlah array 2D berikut menggunakan numpy

In [ ]:
arry = np.array([[4,4,5],[7,6,4],[9,7,4],[6,3,7]])
print('Hasil array 2D adalah:')
print(arry)

Hasil array 2D adalah:
[[4 4 5]
 [7 6 4]
 [9 7 4]
 [6 3 7]]


Buatlah array 3D berikut menggunakan numpy

In [ ]:
arry = np.array([[[7, 8, 5], [4, 7, 7], [7, 1, 9], [5,4,10], [2, 1, 2], [9, 8, 5], [3, 7, 3], [4,9,9], [2, 9, 3], [2, 4, 8], [1, 6, 6], [8,1,3]]])

print('Hasil array 3D adalah:')
print(arry)

Hasil array 3D adalah:
[[[ 7  8  5]
  [ 4  7  7]
  [ 7  1  9]
  [ 5  4 10]
  [ 2  1  2]
  [ 9  8  5]
  [ 3  7  3]
  [ 4  9  9]
  [ 2  9  3]
  [ 2  4  8]
  [ 1  6  6]
  [ 8  1  3]]]


Kode 2

Tambahkan angka 1 pada setipa bilangan di baris ganjil array berikut, kemudian tambahkan angka 2 pada setiap bilangan di kolom genap array berikut

Penambahan angka 1 baris ganjil

In [ ]:
arry = np.array ([[1,8,8,2], [8,2,1,2], [10,1,4,7], [1,4,7,8], [8,2,3,4]])

print ("Matrix nilai sebelum diubah: ")
print (arry)

baris_index = 1,3
arry[baris_index,:] +=1

print('Matrix nilai setelah ditambah 1 baris ganjil :')
print(arry)

Matrix nilai sebelum diubah: 
[[ 1  8  8  2]
 [ 8  2  1  2]
 [10  1  4  7]
 [ 1  4  7  8]
 [ 8  2  3  4]]
Matrix nilai setelah ditambah 1 baris ganjil :
[[ 1  8  8  2]
 [ 9  3  2  3]
 [10  1  4  7]
 [ 2  5  8  9]
 [ 8  2  3  4]]


Penambahan angka 2 baris genap

In [ ]:
arry = np.array ([[1,8,8,2], [8,2,1,2], [10,1,4,7], [1,4,7,8], [8,2,3,4]])
print ("Matrix nilai sebelum diubah: ")
print (arry)

kolom_index = 0,2
arry[:,kolom_index] +=2

print('Matrix nilai setelah ditambah 2 baris genap :')
print(arry)

Baliklah sumbu z array 3D berikut

In [ ]:
#Matrix 3D Normal
arry = np.array([[[7, 8, 5], [4, 7, 7], [7, 1, 9], [5, 4, 10]], [[2, 1, 2], [9, 8, 5], [3, 7, 3], [4, 9, 9]], [[2, 9, 3], [2, 4, 8], [1, 6, 6], [8,1,3]]])

print('Matrix awal sebelum diubah : ')
print(arry)

#Membalikkan sumbu z array 3D
balik = np.flipud(arry)

print('Matrix yang telah di balik :')
print(balik)

Ubahlah array pada soal E menjadi array 2D berukuran 6x6 menggunakan perintah reshape

In [ ]:
#Matrix normal
arry = np.array([[[7, 8, 5], [4, 7, 7], [7, 1, 9], [5, 4, 10]], [[2, 1, 2], [9, 8, 5], [3, 7, 3], [4, 9, 9]], [[2, 9, 3], [2, 4, 8], [1, 6, 6], [8,1,3]]])

print('Matrix awal sebelum diubah : ')
print(arry)

#Membalikkan sumbu z array 3D
balik = np.flipud(arry)
print('Matrix yang telah di balik :')
print(balik)

#Diubah menjadi array 2D 6x6
arry = balik.reshape(6,6)

print('Matrix yang diubah menjadi 6x6')
print(arry)

Kode 3

Ubahlah matriks kiri menjadi matriks sebelah kanan

In [ ]:
array= np.array([[[5, 10, 10, 7], [7,8, 4,10], [9, 10, 2,5], [1, 8, 9,3], [6, 10, 5,2], [4, 6, 9,4]], [[9,3,1,8], [5, 2, 6, 10], [9,4, 4,6], [10, 7, 5,10], [4, 10, 7,8], [2, 5, 9,10]]])

print('Matrix awal sebelum diubah : ')
print(array)

#Ubah matrik kiri ke kanan
ubah_matrix = np.flipud(array)

print('Matrix yang telah di balik : ')
print(ubah_matrix)
